#!/usr/bin/env bash
if [[ $# < 2 ]]; then
    echo "usage: brawn program.brawn executable_path"
    exit 1
fi
DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
FILE=$1
EXE=$2
NAME=$(basename $FILE)
TEMP=$(mktemp -d)
$DIR/_build/default/bin/main.exe $DIR/runtime/brawn_runtime.ll $FILE $TEMP/$NAME.ll
clang++ -ffast-math -finline-functions $TEMP/$NAME.ll $DIR/runtime/brawn_runtime.ll -L$DIR/runtime/deps/gc/.libs/ -o $EXE -lgccpp -lgc
rm -rf $TEMP
