#!/usr/bin/env bash
if [[ $# < 2 ]]; then
    echo "usage: brawn program.brawn executable_path"
    exit 1
fi
DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
FILE=$1
EXE=$2
NAME=$(basename $FILE)
TEMP=$(mktemp -d)
make -C $DIR/runtime > /dev/null
cd $DIR
dune exec brawn $FILE $TEMP/$NAME.ll
llvm-link $DIR/runtime/brawn_runtime.ll $TEMP/$NAME.ll -o $TEMP/program.ll
llc $TEMP/program.ll -o $TEMP/program.s
clang++ -L$DIR/runtime/deps/gc/.libs/ $TEMP/program.s -o $EXE -lgccpp -lgc
rm -rf $TEMP
